#!/usr/bin/env bash
# This script runs indefinitely and handles SIGTERM by printing "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

#!/usr/bin/env bash
# This script stops the 7-highlander process
pkill -f 7-highlander
